name: Executar Aplicação Streamlit

on:
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Certifique-se de que este arquivo existe
          pip install python-dotenv

      - name: Executar a aplicação
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          streamlit run app_melhorado.py
